server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/g-hotel
    username: root
    password: oualid
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    open-in-view: false

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
      file-size-threshold: 2KB
